//! Rendering a set of readings as `docs/performance-baseline.md`.

use std::fmt::Write as _;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use crate::points::{in_group, Group, Point};

use super::stats::{format_duration, Stats};

/// One measurement point's result.
#[derive(Debug, Clone, Copy)]
pub struct Reading {
    pub point: &'static Point,
    pub stats: Stats,
}

/// What produced the numbers.
///
/// Recorded in full because a baseline without it is not comparable with
/// anything — including its own next run on a different machine. The document
/// says so in as many words; this is the evidence behind that sentence.
#[derive(Debug, Clone)]
pub struct Machine {
    /// Model or host description, e.g. `Mac mini (Macmini9,1), 8 cores`.
    pub hardware: String,
    pub os: String,
    pub arch: String,
    /// The exact compiler, which `rust-toolchain.toml` pins (ADR-0139).
    pub toolchain: String,
    /// `YYYY-MM-DD`, from [`today`].
    pub measured_on: String,
    /// Timed iterations per point, after the warm-up ones are discarded.
    pub samples: usize,
}

/// Today's date as `YYYY-MM-DD`, UTC.
///
/// Local time is deliberately not used: it would need a timezone database,
/// and a baseline is dated to the day, not the hour.
#[must_use]
pub fn today() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_secs();
    // `as_secs` is a u64; the divide keeps it well inside i64 for any date
    // this project will see, and `try_from` refuses rather than wrapping.
    let days = i64::try_from(secs / 86_400).unwrap_or(0);
    let (y, m, d) = civil_from_days(days);
    format!("{y:04}-{m:02}-{d:02}")
}

/// Days since 1970-01-01 to a calendar date.
///
/// Howard Hinnant's `civil_from_days`, in `i64` throughout so there are no
/// casts to get wrong. A date is three lines of the baseline document, which
/// is not worth a dependency that brings a timezone database with it.
fn civil_from_days(days: i64) -> (i64, i64, i64) {
    // Shift the epoch to 0000-03-01, so a leap day lands at the end of a
    // year rather than in the middle of one.
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = if month_prime < 10 {
        month_prime + 3
    } else {
        month_prime - 9
    };
    (if month <= 2 { year + 1 } else { year }, month, day)
}

/// The document's opening, before any numbers.
///
/// Kept here rather than in a template file so there is one thing to
/// regenerate and no way for the two to disagree.
fn preamble(machine: &Machine) -> String {
    format!(
        "# Performance baseline\n\
         \n\
         Generated by `cargo run --release -p dbboard-bench -- --write`. Do not\n\
         edit by hand: the next run overwrites it. `--release` is not optional —\n\
         a debug build measures the debug build, and nobody ships one.\n\
         \n\
         `docs/roadmap.md` reserves the v0.14 slot for startup, connect-and-browse\n\
         and large result sets, with the condition that *measurement lands before any\n\
         optimisation, so the numbers are comparable afterwards*. This file is that\n\
         measurement. Nothing here has been optimised yet — these are the numbers as\n\
         they were found.\n\
         \n\
         **These numbers describe one machine.** Comparing a run here against a run\n\
         on different hardware says nothing. Comparing two runs on the same machine,\n\
         across a change, is what the file is for.\n\
         \n\
         No test asserts any number in this file. A threshold on a timing is a flaky\n\
         test, and this project has already paid for one rare intermittent failure\n\
         (ADR-0125). What *is* asserted, by `tests/baseline_drift.rs`, is that the\n\
         measurement points listed here are exactly the ones the harness measures —\n\
         so a point cannot quietly disappear and take its regression with it\n\
         (ADR-0141).\n\
         \n\
         ## What measured this\n\
         \n\
         | | |\n\
         |---|---|\n\
         | Hardware | {hardware} |\n\
         | OS | {os} |\n\
         | Architecture | {arch} |\n\
         | Toolchain | {toolchain} |\n\
         | Measured on | {measured_on} |\n\
         | Timed samples per point | {samples} |\n",
        hardware = machine.hardware,
        os = machine.os,
        arch = machine.arch,
        toolchain = machine.toolchain,
        measured_on = machine.measured_on,
        samples = machine.samples,
    )
}

/// Render the whole document.
///
/// Every group in [`Group::ALL`] gets a heading, in roadmap order. A point
/// with no reading is rendered with dashes rather than skipped: a measurement
/// that failed to run is a fact about the run, and dropping the row would
/// make the drift test the only place it showed up.
#[must_use]
pub fn render_markdown(machine: &Machine, readings: &[Reading]) -> String {
    let mut out = preamble(machine);
    for group in Group::ALL {
        let _ = write!(out, "\n## {}\n\n", group.title());
        out.push_str("| Point | What is timed | Median | p95 | Min | Max |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for point in in_group(group) {
            let found = readings.iter().find(|r| r.point.id == point.id);
            match found {
                Some(r) => {
                    let _ = writeln!(
                        out,
                        "| `{}` | {} | {} | {} | {} | {} |",
                        point.id,
                        point.what,
                        format_duration(r.stats.median),
                        format_duration(r.stats.p95),
                        format_duration(r.stats.min),
                        format_duration(r.stats.max),
                    );
                }
                None => {
                    let _ = writeln!(out, "| `{}` | {} | — | — | — | — |", point.id, point.what);
                }
            }
        }
    }
    out
}

/// The measurement-point identifiers a rendered document lists.
///
/// The parser the drift test uses, kept beside the writer so the two cannot
/// drift from each other: a row is a line starting with `` | ` `` and the id
/// is what sits inside the backticks.
#[must_use]
pub fn ids_in_markdown(text: &str) -> Vec<String> {
    text.lines()
        .filter_map(|line| {
            let rest = line.trim().strip_prefix("| `")?;
            let (id, _) = rest.split_once('`')?;
            Some(id.to_owned())
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{civil_from_days, ids_in_markdown, render_markdown, today, Machine, Reading};
    use crate::harness::Stats;
    use crate::points::{point, POINTS};
    use std::time::Duration;

    fn machine() -> Machine {
        Machine {
            hardware: "Test box, 8 cores".into(),
            os: "testOS 1.0".into(),
            arch: "aarch64".into(),
            toolchain: "1.98.0".into(),
            measured_on: "2026-09-02".into(),
            samples: 50,
        }
    }

    fn reading(id: &str, median_ms: u64) -> Reading {
        Reading {
            point: point(id).expect("a known point"),
            stats: Stats::from_durations(&[Duration::from_millis(median_ms)])
                .expect("one sample summarises"),
        }
    }

    #[test]
    fn the_epoch_is_the_first_of_january_1970() {
        assert_eq!(civil_from_days(0), (1970, 1, 1));
    }

    #[test]
    fn the_day_before_the_epoch_is_the_last_of_december_1969() {
        assert_eq!(civil_from_days(-1), (1969, 12, 31));
    }

    #[test]
    fn a_leap_day_lands_on_the_leap_day() {
        // 2000 is the century that *is* a leap year, which is the case the
        // naive "divisible by four" rule gets wrong.
        assert_eq!(civil_from_days(11_016), (2000, 2, 29));
    }

    #[test]
    fn a_recent_date_round_trips() {
        assert_eq!(civil_from_days(20_698), (2026, 9, 2));
        assert_eq!(civil_from_days(20_088), (2024, 12, 31));
    }

    #[test]
    fn today_is_a_zero_padded_iso_date() {
        let t = today();
        assert_eq!(t.len(), 10, "expected YYYY-MM-DD, got {t}");
        let parts: Vec<&str> = t.split('-').collect();
        assert_eq!(parts.len(), 3);
        assert_eq!(parts[1].len(), 2);
        assert_eq!(parts[2].len(), 2);
        assert!(parts.iter().all(|p| p.chars().all(char::is_numeric)));
    }

    #[test]
    fn the_preamble_records_the_machine() {
        let out = render_markdown(&machine(), &[]);
        assert!(out.contains("Test box, 8 cores"));
        assert!(out.contains("| Toolchain | 1.98.0 |"));
        assert!(out.contains("| Timed samples per point | 50 |"));
    }

    #[test]
    fn the_preamble_says_the_numbers_are_machine_specific() {
        // The one sentence that stops the file being misread. If it is ever
        // edited out, this fails rather than the mistake being made quietly.
        let out = render_markdown(&machine(), &[]);
        assert!(out.contains("These numbers describe one machine."));
    }

    #[test]
    fn every_group_gets_a_heading_in_roadmap_order() {
        let out = render_markdown(&machine(), &[]);
        let startup = out.find("## Startup").expect("startup heading");
        let browse = out.find("## Connect and browse").expect("browse heading");
        let results = out
            .find("## Large result sets")
            .expect("result sets heading");
        assert!(startup < browse && browse < results);
    }

    #[test]
    fn every_catalogued_point_is_rendered_even_without_a_reading() {
        let out = render_markdown(&machine(), &[]);
        let ids = ids_in_markdown(&out);
        let expected: Vec<String> = POINTS.iter().map(|p| p.id.to_owned()).collect();
        assert_eq!(ids, expected);
    }

    #[test]
    fn a_point_without_a_reading_shows_dashes_rather_than_vanishing() {
        let out = render_markdown(&machine(), &[]);
        assert!(out.contains("| `startup/config_paths` | Resolve the platform config directory (`dbboard_config::default_path`) | — | — | — | — |"));
    }

    #[test]
    fn a_reading_renders_its_formatted_durations() {
        let out = render_markdown(&machine(), &[reading("result/serialize_10k", 41)]);
        assert!(
            out.contains("| `result/serialize_10k` |") && out.contains("41.0 ms"),
            "expected the reading's median in the table, got:\n{out}"
        );
    }

    #[test]
    fn ids_in_markdown_ignores_prose_and_the_machine_table() {
        let text = "# Title\n\nSome `code` in prose.\n\n| | |\n|---|---|\n| OS | x |\n| `a/b` | what | 1 ms | 2 ms | 0 ms | 3 ms |\n";
        assert_eq!(ids_in_markdown(text), vec!["a/b".to_owned()]);
    }
}
